### ISSUE TITLE
Missing mudule in LUA

### ISSUE THREAD

**Issue by tinycorelinux** [hg2ecz/ProgrammingLanguageBenchmark-FFT_4096#9]
Running LUA I get this error. With LUAJIT it works fine.

lua: benchmark.lua:3: module 'bit' not found:
        no field package.preload['bit']
        no file '/usr/local/share/lua/5.2/bit.lua'
        no file '/usr/local/share/lua/5.2/bit/init.lua'
        no file '/usr/local/lib/lua/5.2/bit.lua'
        no file '/usr/local/lib/lua/5.2/bit/init.lua'
        no file './bit.lua'
        no file '/usr/local/lib/lua/5.2/bit.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './bit.so'
stack traceback:
        [C]: in function 'require'
        benchmark.lua:3: in main chunk
        [C]: in ?

**Comment by hg2ecz** [comment]
Please install package "lua-bitop" (Debian, Ubuntu), because the bit manipulator functions are part of luajit but not included in classic lua interpreter.
